name: "Format sources"
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git pkg-config build-essential meson libsdl2-dev libreadline-dev dfu-util cmake libusb-1.0-0 libusb-1.0-0-dev
      - name: build install codec2
        run: |
          cd ${{github.workspace}}
          meson subprojects download
          cd subprojects/codec2
          mkdir build_linux
          cd build_linux
          cmake ..
          make
          sudo make install
      - name: setup meson
        run: |
          cd ${{github.workspace}}
          meson setup build
      - name: Trade out pre-installed clang-format with clang-format-16
        run: |
          which clang-format
          clang-format --version
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
          sudo apt-get install -y clang-format-16
          sudo rm -rf /usr/bin/clang-format
          sudo ln -s /usr/bin/clang-format-16 /usr/bin/clang-format
          which clang-format
          which clang-format-16
          clang-format --version
          clang-format-16 --version
      - name: Check if there are format errors
        run: ninja -C build clang-format-check
